[project]
authors = [{name = "Sam Van Stroud", email = "sam.van.stroud@cern.ch"}]
dependencies = [ "pytest>=8.3.3,<9", "setuptools>=75.5.0,<76", "ruff==0.8.0", "pre-commit>=4.0.1,<5", "einops>=0.8.0,<0.9", "matplotlib>=3.9.2,<4"]
description = "Attention for High Energy Physics"
license = { text = "MIT" }
readme = "README.md"
name = "hepattn"
requires-python = "== 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["nvidia", "pytorch", "conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
hepattn = { path = ".", editable = true }

[tool.pixi.system-requirements]
linux = "3.10.0"
libc = "2.17"
cuda = "12.3"

[tool.pixi.dependencies]
pytorch-cuda = "12.1.*"
pytorch = "2.5.1.*"
numpy = ">=2.1.3,<3"
gcc = ">=14.2.0,<14.3"

[tool.ruff]
src = ["src"]
target-version = "py311"
line-length = 150
preview = true
lint.select = ["ALL"]
lint.ignore = ["G", "D", "ANN", "PLW", "FBT", "COM812", "ISC001", "CPY001", "TRY003", "S101", "A003", "N812", "PLR0913", "PLR0917", "DOC201", "INP001", "PLR6301", "T201"]
