[project]
authors = [{name = "Sam Van Stroud", email = "sam.van.stroud@cern.ch"}]
description = "Attention for High Energy Physics"
license = { text = "MIT" }
readme = "README.md"
name = "hepattn"
requires-python = "== 3.11"
version = "0.1.0"
dependencies = [
    "pytest>=8.3.3,<9",
    "setuptools>=75.5.0,<76",
    "ruff==0.8.0",
    "pre-commit>=4.0.1,<5",
    "einops>=0.8.0,<0.9",
    "matplotlib>=3.9.2,<4",
    "lightning>=2.4.0,<3",
    "comet-ml>=3.47.3,<4",
    "pandas>=2.2.3,<3",
    "pyarrow>=18.0.0,<19",
    "numpy>=2.1.3,<3",
    "jsonargparse[signatures]>=4.34.0,<5",
    "flash-attn>=2.7.0.post2,<3",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["nvidia", "pytorch", "conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
hepattn = { path = ".", editable = true }

[tool.pixi.system-requirements]
linux = "3.10.0"
libc = "2.17"
cuda = "12.3"

[tool.pixi.dependencies]
pytorch-cuda = "12.1.*"
pytorch = "2.5.1.*"
gcc = ">=14.2.0,<14.3"

[tool.pixi.pypi-options]
no-build-isolation = ["flash-attn"]

[tool.ruff]
src = ["src"]
target-version = "py311"
line-length = 150
preview = true
lint.select = ["ALL"]
lint.ignore = ["G", "D", "DOC", "ANN", "PLW", "FBT", "EM", "PLR1714", "PLR2004", "PT018", "RET504", "COM812", "ISC001", "CPY001", "TRY003", "S101", "A003", "N812", "PLR0913", "PLR0917", "DOC201", "INP001", "PLR6301", "T201"]
