name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/prefix-dev/pixi:0.45.0-noble-cuda-12.6.3
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Step 2: Set up Pixi
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.48.1
          cache: true
          locked: true
      # Step 3: Build Pixi environment using the lockfile and pyproject.toml
      - name: Install Pixi Environment
        run: pixi install --locked --file ./pyproject.toml
      # Step 4: Verify Pixi environment
      - name: Verify Pixi Environment
        run: pixi check
