name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/prefix-dev/pixi:0.45.0-noble-cuda-12.6.3
    steps:
      - uses: actions/checkout@v4
      - name: Free disk space
        run: |
          rm -rf /usr/local/lib/android
          rm -rf /opt/ghc
          rm -rf /usr/share/dotnet
          rm -rf /usr/local/share/boost
          rm -rf /usr/local/.ghcup
          df -h
      - name: Build Pixi Environment
        run: |
          pixi install --locked
