name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/prefix-dev/pixi:0.45.0-noble-cuda-12.6.3
    steps:
      - uses: actions/checkout@v4
      - name: Build Pixi Environment
        run: |
          pixi install --file ./pyproject.toml --locked
