name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Setup Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.8.0"
          args: "--version"

      - name: Where am I
        run: pwd && ls -la

      - name: Run ruff check
        run: ruff -v --config ./pyproject.toml check --fix

      - name: Check python version
        run: python --version

      - name: Run ruff format
        run: ruff -v --config ./pyproject.toml format

      #- name: Run pyright
      #  run: uv run pyright
