name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Run ruff check
        run: ruff -v --config ./pyproject.toml check --fix

      - name: Run ruff format
        run: ruff -v --config ./pyproject.toml format

      #- name: Run pyright
      #  run: uv run pyright
